/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PayrollRouterInterface extends Interface {
  getFunction(
    nameOrSignature: "recordPayment" | "usdctToken"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Paid"): EventFragment;

  encodeFunctionData(
    functionFragment: "recordPayment",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "usdctToken",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "recordPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdctToken", data: BytesLike): Result;
}

export namespace PaidEvent {
  export type InputTuple = [
    invoiceId: BytesLike,
    payer: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    invoiceId: string,
    payer: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    invoiceId: string;
    payer: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PayrollRouter extends BaseContract {
  connect(runner?: ContractRunner | null): PayrollRouter;
  waitForDeployment(): Promise<this>;

  interface: PayrollRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  recordPayment: TypedContractMethod<
    [
      invoiceId: BytesLike,
      payer: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  usdctToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "recordPayment"
  ): TypedContractMethod<
    [
      invoiceId: BytesLike,
      payer: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdctToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Paid"
  ): TypedContractEvent<
    PaidEvent.InputTuple,
    PaidEvent.OutputTuple,
    PaidEvent.OutputObject
  >;

  filters: {
    "Paid(bytes32,address,address,uint256)": TypedContractEvent<
      PaidEvent.InputTuple,
      PaidEvent.OutputTuple,
      PaidEvent.OutputObject
    >;
    Paid: TypedContractEvent<
      PaidEvent.InputTuple,
      PaidEvent.OutputTuple,
      PaidEvent.OutputObject
    >;
  };
}
