/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../common";
import type { PayrollRouter, PayrollRouterInterface } from "../PayrollRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_usdctToken",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Paid",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "invoiceId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "recordPayment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "usdctToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516101fc3803806101fc83398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b610169806100936000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063c71415181461003b578063d9d2afca14610050575b600080fd5b61004e6100493660046100ef565b61007f565b005b600054610063906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b816001600160a01b0316836001600160a01b0316857f37db9851b6c9a32f8ddcf4734e6526de7c85268ef735f7883ea70dc8a39c9c85846040516100c591815260200190565b60405180910390a450505050565b80356001600160a01b03811681146100ea57600080fd5b919050565b6000806000806080858703121561010557600080fd5b84359350610115602086016100d3565b9250610123604086016100d3565b939692955092936060013592505056fea2646970667358221220ff7491e76b341ff592aa4e71154ce6e27c054a63d8575fec15bedc9bc016ebe564736f6c63430008140033";

type PayrollRouterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PayrollRouterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PayrollRouter__factory extends ContractFactory {
  constructor(...args: PayrollRouterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _usdctToken: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_usdctToken, overrides || {});
  }
  override deploy(
    _usdctToken: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_usdctToken, overrides || {}) as Promise<
      PayrollRouter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PayrollRouter__factory {
    return super.connect(runner) as PayrollRouter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PayrollRouterInterface {
    return new Interface(_abi) as PayrollRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PayrollRouter {
    return new Contract(address, _abi, runner) as unknown as PayrollRouter;
  }
}
